Set the `cliPath` in the SDK
The Copilot SDK package uses `const sdkUrl = import.meta.resolve("@github/copilot/sdk");` to find its location on disk, and from there finds the location of the Copilot CLI from the @github/copilot package (or really, a .js file that wraps the CLI, but that isn't relevant).

The `import.meta.resolve` just does not work when running test code through Jest, so the test run quickly dies with an error like:

```
  ● azure-deploy_ - Integration Tests › static-web-apps-deploy › creates whiteboard application

    TypeError: (intermediate value).resolve is not a function

      368 |       }
      369 |
    > 370 |       const client = new CopilotClient({
          |                      ^
      371 |         logLevel: process.env.DEBUG ? "all" : "error",
      372 |         cwd: testWorkspace,
      373 |         cliArgs: cliArgs,

      at getBundledCliPath (node_modules/@github/copilot-sdk/dist/client.js:31:30)
      at new CopilotClient (node_modules/@github/copilot-sdk/dist/client.js:105:35)
      at Object.run (utils/agent-runner.ts:370:22)
      at async Object.<anonymous> (azure-deploy/integration.test.ts:104:29)
```

Here we hack around this by finding the path to the CLI ourselves and passing it in via the `cliPath` property.